spring:
  application.name: auth-jwt-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: trace
      springframework: info
      hibernate: info

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond