# consumer server port
server:
  port: 8082


# broker config
spring:
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: adminpass
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: async-data
