version: '3.8'
services:
  spring-app:
    build:
      context: .
      dockerfile: spring.dockerfile
    container_name: spring-caching
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db
  postgres-db:
    image: 'postgres:15-alpine'
    restart: always
    container_name: postgres-15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=something
      - POSTGRES_DB=productdb
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
volumes:
  db: null
