services:
  react-app:
    build:
      context: .
      dockerfile: react.dockerfile
    image: simple-react-app:latest
    container_name: rect-app
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped